# Generated by Django 2.0.6 on 2018-06-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0003_auto_20180624_0809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='evaluator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teleapp.Employees'),
        ),
        migrations.AddField(
            model_name='employees',
            name='status',
            field=models.CharField(choices=[('A', 'Admin'), ('M', 'Manager'), ('S', 'Supervisor'), ('C', 'Coach'), ('J', 'Junior Staff')], default='N', max_length=1),
        ),
    ]
