# Generated by Django 2.0.6 on 2018-06-25 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0004_auto_20180624_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='evaluator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teleapp.Employees'),
        ),
    ]
