# Generated by Django 2.0.6 on 2018-06-25 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0005_auto_20180625_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='evaluator',
        ),
    ]
