# Generated by Django 2.0.6 on 2018-06-25 04:57

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teleapp', '0006_remove_employees_evaluator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Admin'), ('M', 'Manager'), ('S', 'Supervisor'), ('C', 'Coach'), ('J', 'Junior Staff')], default='N', max_length=1)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='employees',
            name='user',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
