# Generated by Django 2.0.6 on 2018-06-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0007_auto_20180625_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
    ]
