# Generated by Django 2.0.6 on 2018-06-25 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teleapp', '0008_auto_20180625_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='evaluator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teleapp.Employee'),
        ),
    ]
